### ISSUE TITLE
A6 work unstable.

### ISSUE THREAD

**Issue by likewwddaa** [vshymanskyy/TinyGSM#24] opened 2017-04-05 13:05 UTC
Hi!
 I use a A7mini +mega2560 with sample mqtt code.Seems work good,but after hours,it can't connect to my
mqtt sever. The module 's  blue led blinks once a second. I can't solve .Could u help me?

**Comment by vshymanskyy** [comment] 2017-05-16 05:59
Duplicate of #30

**Closed by vshymanskyy** 2017-05-16 05:59 UTC
