### ISSUE TITLE
mqtt Client connection delay

### ISSUE THREAD

**Issue by sankaramp** [vshymanskyy/TinyGSM#149] opened 2018-04-04 06:50 UTC
hello,
I'm using this library for MQTT Client and Broker communication..
my Problem is "taking much more time for connection (function:  mqttConnect(); ) and sometimes connection failed also.
I want to publish data to MQTT-Broker for every 10mins interval.

plz give me suggetions to solve this.

regards,
Sankar.

**Comment by vshymanskyy** [comment] 2018-04-05 18:01
Closing as the issue is not well-documented. Please follow the issue template

**Closed by vshymanskyy** 2018-04-05 18:01 UTC
